wfcassandra:
  image: wfdemo/wildfly-cassandra
  ports:
   - "9990:9990"
   - "9042:9042"
wfapp:
  image: wfdemo/wildfly
  links:
   - wfcassandra:cassandra
  ports:
   - "8080:8080"
   - "9991:9990"
flyng:
  image: wfdemo/fly-ng
  ports:
   - "80:80"
